// Generated by CIRCT firtool-1.43.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// VCS coverage exclude_file
module memory_combMem(	// src/main/scala/gcd/GradProject.scala:14:19
  input  [9:0]  R0_addr,
  input         R0_en,
                R0_clk,
  input  [9:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data,
  input  [9:0]  W1_addr,
  input         W1_en,
                W1_clk,
  input  [31:0] W1_data,
  output [31:0] R0_data
);

  reg [31:0] Memory[0:1023];	// src/main/scala/gcd/GradProject.scala:14:19
  always @(posedge W0_clk) begin	// src/main/scala/gcd/GradProject.scala:14:19
    if (W0_en)	// src/main/scala/gcd/GradProject.scala:14:19
      Memory[W0_addr] <= W0_data;	// src/main/scala/gcd/GradProject.scala:14:19
    if (W1_en)	// src/main/scala/gcd/GradProject.scala:14:19
      Memory[W1_addr] <= W1_data;	// src/main/scala/gcd/GradProject.scala:14:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/gcd/GradProject.scala:14:19
    reg [31:0] _RANDOM_MEM;	// src/main/scala/gcd/GradProject.scala:14:19
    initial begin	// src/main/scala/gcd/GradProject.scala:14:19
      `INIT_RANDOM_PROLOG_	// src/main/scala/gcd/GradProject.scala:14:19
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/gcd/GradProject.scala:14:19
        for (logic [10:0] i = 11'h0; i < 11'h400; i += 11'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/gcd/GradProject.scala:14:19
          Memory[i[9:0]] = _RANDOM_MEM;	// src/main/scala/gcd/GradProject.scala:14:19
        end	// src/main/scala/gcd/GradProject.scala:14:19
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/gcd/GradProject.scala:14:19
endmodule

module InstructionMemory(	// <stdin>:3:10
  input         clock,	// <stdin>:4:11
                reset,	// <stdin>:5:11
  input  [9:0]  io_address,	// src/main/scala/gcd/GradProject.scala:8:14
  output [31:0] io_instruction	// src/main/scala/gcd/GradProject.scala:8:14
);

  memory_combMem memory_ext (	// src/main/scala/gcd/GradProject.scala:14:19
    .R0_addr (io_address),
    .R0_en   (1'h1),	// <stdin>:3:10
    .R0_clk  (clock),
    .W0_addr (10'h0),	// src/main/scala/gcd/GradProject.scala:18:11
    .W0_en   (1'h1),	// <stdin>:3:10
    .W0_clk  (clock),
    .W0_data (32'h0),	// src/main/scala/gcd/GradProject.scala:18:18
    .W1_addr (10'h1),	// src/main/scala/gcd/GradProject.scala:18:11
    .W1_en   (1'h1),	// <stdin>:3:10
    .W1_clk  (clock),
    .W1_data (32'h0),	// src/main/scala/gcd/GradProject.scala:18:18
    .R0_data (io_instruction)
  );
endmodule

